# Generated by Django 5.1.1 on 2024-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin1', models.CharField(blank=True, max_length=11, null=True)),
                ('admin2', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
