# Generated by Django 5.1.1 on 2024-10-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_adminnumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
